### ISSUE TITLE
fastinteger.FastIntegerHashMap delete does not rehash current cluster of packets

### ISSUE THREAD

**Issue by mmalone** [Workiva/go-datastructures#120]
When a "packet" is deleted from FastIntegerHashMap subsequent packets are not rehashed. If three packets are inserted that hash to the same position, then the second one is deleted, then a get of the third one is performed, the get will fail because a nil value for the second packet will be located before the third item is encountered during linear probing. Here's a quick test case:

```go
func TestDeleteCollision(t *testing.T) {
    // 1, 27, 42 all hash to the same value using our hash function % 32
    if hash(1)%32 != 12 || hash(27)%32 != 12 || hash(42)%32 != 12 {
        t.Error("test values don't hash to the same value")
    }

    m := New(32)
    m.Set(1, 1)
    m.Set(27, 27)
    m.Set(42, 42)

    m.Delete(27)
    value, ok := m.Get(42)
    assert.True(t, ok)
    assert.Equal(t, uint64(42), value)
}
```

And here's a modified delete method that fixes the issue:

```go
func (packets packets) delete(key uint64) bool {
    i := packets.find(key)
    if packets[i] == nil {
        return false
    }
    packets[i] = nil
    i = (i + 1) & (uint64(len(packets)) - 1)
    for packets[i] != nil {
        p := packets[i]
        packets[i] = nil
        packets.set(p)
        i = (i + 1) & (uint64(len(packets)) - 1)
    }
    return true
}
```

Alternatively, you could use a sentry/tombstone element to mark things that are "deleted" instead of `nil`ing them out, which would probably be faster for most typical use cases but cost more in memory.

**Comment by mmalone** [comment]
I just checked TAOCP and Knuth suggests another algorithm. I don't have an implementation (yet), but if you're interested check out Volume 3, Section 6.4 (it's page 533-534 in the newest edition). He claims it results in no performance degradation (on an average complexity basis). Cursory Googling shows some debate and a couple different techniques that are used. The implementation above seems the most intuitive (to me), but possibly sub-optimal.

Seems like something worth nerding out on at some point. Will report back if I come up with any code worth sharing.

**Comment by dustinhiatt-wf** [comment]
@mmalone Awesome, thanks for the fix!  https://github.com/Workiva/go-datastructures/pull/121

I'm also swamped right now, but if you come up with the optimal fix we can certainly get it merged.

**Comment by dustinhiatt-wf** [comment]
Any further work I'll consider to be an improvement so I'm closing this as a bug ticket.
