### ISSUE TITLE
ctrie: hasherPool poor performance

### ISSUE THREAD

**Issue by newhook** [Workiva/go-datastructures#125]
I found getting rid of the hasher pool made a pretty big difference in the performance of the ctrie imp (I can't remember exactly how much but I think it was ~5% performance improvement).

**Comment by tylertreat-wf** [comment]
Interesting. The hasher pool was added as a perf optimization to avoid locking. Thought I benchmarked it. Will have to take another look at it. Maybe its size just needs to be increased if we're waiting on it a lot in high concurrency situations.

**Comment by newhook** [comment]
I just had a look for the perf graph I generated before & after and unfortunately its gone. However, if I recall correctly the pool queue was pretty porky in the graph.

**Comment by tylertreat** [comment]
What did you replace the hasher pool with?

**Comment by newhook** [comment]
I didn't pool at all, just allocate a new hasher each time.

**Comment by tylertreat-wf** [comment]
Fixed in #128.
