### ISSUE TITLE
ctrie: iterator performance

### ISSUE THREAD

**Issue by newhook** [Workiva/go-datastructures#129]
I've been comparing an implementation of a database cache using ctrie & the immutable avl tree. The ctrie is more efficient except when iterating. I think the ctrie iteration scheme of using a goroutine and channel gives pretty bad performance compared to the straight traversal of the avl tree nodes, plus the channel is prone to leakage (as noted in the code).

**Comment by tylertreat-wf** [comment]
Yeah, I'm not super thrilled with the current iterator implementation. Happy to accept PRs for it.

**Comment by newhook** [comment]
I'm experimenting with this impl I just whipped up. Its still very very slow. Still digging... not sure if you have insight?

```
type istate struct {
	array []branch
	l     PersistentList
	index int
}

func newIState(i *iNode, c *Ctrie) *istate {
	main := gcasRead(i, c)
	switch {
	case main.cNode != nil:
		return &istate{
			array: main.cNode.array,
		}

	case main.lNode != nil:
		return &istate{
			l: main.lNode,
		}
	}
	return nil
}

type Iterator struct {
	c     *Ctrie
	stack []*istate
}

// Next ...
func (i *Iterator) Next() *Entry {
	for {
		if len(i.stack) == 0 {
			return nil
		}

		state := i.stack[len(i.stack)-1]
		if state.array != nil {
			if state.index >= len(state.array) {
				i.stack = i.stack[:len(i.stack)-1]
				continue
			}

			br := state.array[state.index]
			state.index++

			switch b := br.(type) {
			case *iNode:
				// start := time.Now()
				ns := newIState(b, i.c)
				// fmt.Println("newIstate: ", time.Now().Sub(start))
				i.stack = append(i.stack, ns)

			case *sNode:
				return b.Entry
			}
		} else {
			if state.l == nil {
				i.stack = i.stack[:len(i.stack)-1]
				continue
			}
			head, ok := state.l.Head()
			if !ok {
				i.stack = i.stack[:len(i.stack)-1]
				continue
			}
			state.l, _ = state.l.Remove(0)

			return head.(*sNode).Entry
		}
	}
}

// Iterator returns a channel which yields the Entries of the Ctrie. If a
// cancel channel is provided, closing it will terminate and close the iterator
// channel. Note that if a cancel channel is not used and not every entry is
// read from the iterator, a goroutine will leak.
func (c *Ctrie) Iterator2() *Iterator {
	snapshot := c.ReadOnlySnapshot()
	return &Iterator{
		c:     snapshot,
		stack: []*istate{newIState(snapshot.readRoot(), snapshot)},
	}
}
```

**Comment by tylertreat-wf** [comment]
Looks more or less how I'd implement a stateful iterator. Glancing over it, I don't see any immediately obvious issues. Surprised the performance isn't much better than the goroutine/channel.

**Comment by newhook** [comment]
Actually, I think its faster. I was confused in my benchmark but other databasey factors :) That said on a performance note, after your ctrie fix for the generations the ctrie is substantially slower. My profiling of lots of inserts shows 16% of the time in gcasRead/atomic.LoadPointer.

**Comment by tylertreat-wf** [comment]
Individual operations not under contention appear to be about the same, though snapshotting is substantially faster after the fix:

Before GCAS fix:
```
BenchmarkInsert-8                3000000               488 ns/op
BenchmarkLookup-8               10000000               208 ns/op
BenchmarkRemove-8               10000000               196 ns/op
BenchmarkSnapshot-8              1000000              2061 ns/op
BenchmarkReadOnlySnapshot-8      1000000              2007 ns/op
```

After GCAS fix:
```
BenchmarkInsert-8                3000000               443 ns/op
BenchmarkLookup-8               10000000               173 ns/op
BenchmarkRemove-8               10000000               156 ns/op
BenchmarkSnapshot-8              5000000               350 ns/op
BenchmarkReadOnlySnapshot-8      5000000               263 ns/op
```

I imagine under high contention on certain parts of the ctrie, performance will degrade due to retries now that GCAS actually works. Would be nice to get benchmarking around contention.

What do the access patterns look like in your profiling? High contention on same keys?

**Comment by newhook** [comment]
No, my test basically wrote 1000000 unique items into the ctree serially.

**Comment by tylertreat-wf** [comment]
Can you quantify "substantially slower"? Following from the benchmarks above, I'm not sure how it would be slower in a single-threaded case.

**Comment by newhook** [comment]
My test case shows ctrie.Insert at 16.75s with the new ctrie and 1.76s with the old. The test isn't standalone (it has lots of other stuff in there), but that part of the profile stood out to me.

![prof2](https://cloud.githubusercontent.com/assets/10376697/12125027/7e7269ba-b3c3-11e5-971a-80fc98fc1783.png)
![prof1](https://cloud.githubusercontent.com/assets/10376697/12125026/7e60151c-b3c3-11e5-9f99-495929ab523e.png)

**Comment by tylertreat-wf** [comment]
Do you have a lot of snapshotting going on? It looks like the performance degradation is due to renewed/copyToGen which is caused by a snapshot. Snapshots are essentially lazily applied by copying nodes to the new generation as they are accessed, so if there are a lot of snapshots, nodes will potentially get copied a lot of times.

**Comment by newhook** [comment]
Yes, I essentially have a transactional data model, So each write transaction creates snapshots of the data and then alters the snapshot. On commit the snapshot is swapped with the formerly comittted data.

**Comment by tylertreat-wf** [comment]
That's likely the cause of the performance slowdown since snapshotting was pretty much broken before the fix. Though indeed I am surprised `renewed` is that expensive.

**Comment by newhook** [comment]
Yeah, makes sense. I think I can rearrange the implementation to snapshot differently to avoid the additional overhead.

**Comment by alexandercampbell-wf** [comment]
Closing as stale. @newhook please re-open if you think this requires further discussion :)
