### ISSUE TITLE
using augmentedtree with non-integer intervals

### ISSUE THREAD

**Issue by tamird** [Workiva/go-datastructures#130]
In our use case, each interval's start and end are of type `[]byte`.

Is it possible to use `augmentedtree` for this use case? Seems like we'd quickly overflow the `int64` return required by `Interval.{Low,High}AtDimension`.

**Comment by dustinhiatt-wf** [comment]
Yeah, you'd overflow the int64 in a lot of cases.  Unfortunately, only way to support []byte is to copy/paste the tree or use interface{}.  I'm not opposed to having those things, just don't have time to do that myself.

**Comment by alexandercampbell-wf** [comment]
Closing, since we don't have the resources to customize the `augmentedtree` for the other Golang types. Feel free to open a PR.
