### ISSUE TITLE
Using augmented tree to find which interval a point is in is failing

### ISSUE THREAD

**Issue by jagandecapri** [Workiva/go-datastructures#176]
Hi, 

My goal is to find which interval a **point** is in. I am under the impression that this is possible with augmentedtree package based on the documentation [here](https://godoc.org/github.com/golang-collections/go-datastructures/augmentedtree) stating 

>  You can also check intersections against a point by constructing a range of encompassed solely if a single point.

Hence, I have constructed an augmented tree containing a single 2D interval having lows at [0,0] and highs at [1,1]. However, when I tried to query which interval that the point (0,0) is in, I am getting an empty result. Any help is much appreciated.

Code snippet:

```Go
type IntervalContainerTest struct {
	Id           int
	Low          []int64
	High         []int64
}

func (itv IntervalContainerTest) LowAtDimension(dim uint64) int64{
	return itv.Low[dim - 1]
}

func (itv IntervalContainerTest) HighAtDimension(dim uint64) int64{
	return itv.High[dim - 1]
}

// OverlapsAtDimension should return a bool indicating if the provided
// interval overlaps this interval at the dimension requested.
func (itv IntervalContainerTest) OverlapsAtDimension(interval augmentedtree.Interval, dim uint64) bool{
	check := false
	if interval.LowAtDimension(dim) <= itv.HighAtDimension(dim) &&
		interval.HighAtDimension(dim) >= itv.LowAtDimension(dim){
		check = true
	} else {
		check = false
	}
	return check
}

func (itv IntervalContainerTest) ID() uint64{
	return uint64(itv.Id)
}

func TestIntervalQueryInt(t *testing.T){
	tree := NewIntervalTree(2)
	intervals_container := IntervalContainerTest{Id: 1, Low: []int64{0, 0}, High: []int64{1, 1}}
	intervals := augmentedtree.Interval(intervals_container)
	tree.Add(intervals)

	interval_test_query := tree.Query(IntervalContainerTest{Id: 1, Low: []int64{0, 0}, High: []int64{0, 0}})
	assert.Len(t, interval_test_query, 1, "Interval not found: %v", interval_test_query)
}
```

Result:

```
--- FAIL: TestIntervalQueryInt (0.00s)
        ......
        Error:          "[]" should have 1 item(s), but has 0
```

**Comment by jagandecapri** [comment]
Hei @alexandercampbell-wf @dustinhiatt-wf, any help on the above question? :)

**Comment by dustinhiatt-wf** [comment]
@jagandecapri I'll take a look this afternoon/tonight.

**Comment by dustinhiatt-wf** [comment]
@jagandecapri tossed [this code](https://gist.github.com/dustinhiatt-wf/89b79272f49340048e91ce0014b2915d) into the augmentedtree package and ran the test.  It seemed to pass:

`~/projects/src/github.com/Workiva/go-datastructures/augmentedtree (check-interval-tree) $ go test -run TestIntervalQueryInt$ -v
=== RUN   TestIntervalQueryInt
--- PASS: TestIntervalQueryInt (0.00s)
PASS
ok  	github.com/Workiva/go-datastructures/augmentedtree	0.016s`

**Comment by jack-zalora** [comment]
@dustinbraun-wf I identified where was the mistake in my code. I was importing `github.com/golang-collections/go-datastructures/augmentedtree`. Noticed that it should be `github.com/Workiva/go-datastructures/augmentedtree`. My mistake. Thanks for checking on this.

**Comment by jagandecapri** [comment]
@dustinbraun-wf I identified where was the mistake in my code. I was importing github.com/golang-collections/go-datastructures/augmentedtree. Noticed that it should be github.com/Workiva/go-datastructures/augmentedtree. My mistake. Thanks for checking on this.

**Comment by dustinhiatt-wf** [comment]
👍
