### ISSUE TITLE
Get from PriorityQueue

### ISSUE THREAD

**Issue by kenenbek** [Workiva/go-datastructures#183]
This snippet of code gives me:
```
func main() {
	myqueue := queue.NewPriorityQueue(20, true)
	myqueue.Put(Myfloat(4))
	myqueue.Put(Myfloat(-1))
	myqueue.Put(Myfloat(-99))
	myqueue.Put(Myfloat(104))

	result, _ := myqueue.Get(3)
	fmt.Println(result)
}
```
`[-99 -1]`

While I expected `[-99 -1 4]`

Why did it happen? 

P.S Compare method for `Item` interface.
```
type Myfloat float32

func (mi Myfloat) Compare(other queue.Item) int {
	omi := other.(Myfloat)
	if mi > omi {
		return 1
	} else if mi == omi {
		return 0
	}
	return -1
}
```

**Comment by andreis** [comment]
I've noticed this as well, `.Get` only returns half of `min(number, pq.Len())`. It's really annoying, and I have no idea what causes it.

**Comment by andreis** [comment]
Nvm

https://github.com/Workiva/go-datastructures/blob/master/queue/priority_queue.go#L79

This should be 
```
if len(*items) == 0
```


cc @dustinhiatt-wf @ichinaski
