### ISSUE TITLE
Breaking API changes in satori/go.uuid

### ISSUE THREAD

**Issue by iancmcc** [Workiva/go-datastructures#187]
The changes outlined in https://github.com/satori/go.uuid/issues/66 break the btree/immutable package. I guess the changes may or may not be reverted, based on the comments, but a fix might be in order.

**Comment by nightrune** [comment]
I just hit this as well. I don't need btree yet so its not urgent, but this has been opened for 22 days.

**Comment by rsc** [comment]
I sent a PR removing go.uuid entirely. It was not contributing much.
