### ISSUE TITLE
Future

### ISSUE THREAD

**Issue by funny-falcon** [Workiva/go-datastructures#61]
I think it is better to make future to look like
````go
type Future struct {
    m sync.Mutex
    val interface{}
    err error
    wait chan struct{}
    filled bool
    timeout *time.Timer
}

func NewFuture(d time.Duration) (f *Future) {
    ch := make(chan struct{})
    f = &Future { wait: ch }
    if d > 0 {
        f.timeout = time.AfterFunc(d, f.timedout)
    }
    return
}

func (f *Future) timedout() {
    f.m.Lock()
    if !f.filled {
        f.err = errors.New("timeout")
        close(f.wait)
        f.filled = true
        f.timeout = nil
    }
    f.m.Unlock()
}

func (f *Future) Fill(val interface{}) (err error) {
    f.m.Lock()
    if !f.filled {
        f.val = val
        if f.timeout != nil {
            f.timeout.Stop()
            f.timeout = nil
        }
        close(f.wait)
        f.filled = true
    } else if (f.err != nil) {
        err = f.err
    } else {
        err = errors.New("already filled")
    }
    f.m.Unlock()
    return
}

func (f *Future) Wait() <-chan struct{} {
    return f.wait
}

func (f *Future) Value() (interface{}, error) {
    /* normally one will call f.Value() only after f.Wait() already closed,
       but lets check it once again */
    <- f.wait
    return f.val, f.err
}
````
Not tested.

**Comment by tmm1** [comment]
Futures can also be implemented elegantly using a self-pumping channel:http://thegozette.com/articles/2011/05/11/futures-revisited/

**Comment by funny-falcon** [comment]
@tmm1 unfortunately, thegozette is not available :-( (at least, from my network)
can you describe that approach?

**Comment by tmm1** [comment]
Basically everytime you receive a value from the channel, you send the value back to the channel for the next receiver.

```go
future := make(chan bool, 1)
go func() {
  time.Sleep(2 * time.Second)
  future <- true
}()

var w sync.WaitGroup
for n := 0; n < 10; n++ {
  w.Add(1)
  go func() {
    val := <-future
    future <- val
    w.Done()
  }()
}

w.Wait()
```

**Comment by funny-falcon** [comment]
No, it is not elegant. It is error prone and inefficient.
Error prone, cause there is no way to determine if value already set (cause channel may be empty between fetching from and sending back), so that value could be set twice or more times.
Inefficient, cause it wakes waiters serially. Closing channel wakes all waiters at once, so does WaitGroup.

**Comment by alexandercampbell-wf** [comment]
@funny-falcon sorry it's taken us so long to look at your suggestion. What is the advantage to making this change? The only difference in the public-facing API appears to be the introduction of a `Wait()` method, which can already be achieved by calling [`future.GetResult()`](https://github.com/Workiva/go-datastructures/blob/93a32f65cc34e5c27a36b0907a0060fa8f7b3bcd/futures/futures.go#L52) and ignoring the output.

**Comment by funny-falcon** [comment]
@alexandercampbell-wf , no, difference in an API is huge.
With my proposal, there is ability to wait future with external `select`.

That means, one can:
- wait several futures at once
- wait future and timeout (now I think, timeout should not be part of a future itself, but rather add `Cancel` public method)
- wait future and not future (for example, waiting on net.Context.Done() channel https://godoc.org/golang.org/x/net/context#Context.Done ).

This make api much more flexible.

I understand, that avoiding channels it a performance issue. Maybe, two Futures should co-exists in a library - one with WaitGroup for waiting, and other with channel.

**Comment by alexandercampbell-wf** [comment]
@funny-falcon ah, I didn't see that `Wait()` was returning a channel.

We've hit many issues with channels in the past, so I'd prefer to preserve our existing struct. But I'd be ok with adding a `SelectableFuture` type to the `future` package. Does that sound good to you?

**Comment by funny-falcon** [comment]
Yes, it is good.
Shall I make a pull request?

**Comment by alexandercampbell-wf** [comment]
@funny-falcon sure.

**Comment by funny-falcon** [comment]
added https://github.com/Workiva/go-datastructures/pull/137
