### ISSUE TITLE
Race Condition in Ctrie Tests

### ISSUE THREAD

**Issue by alexandercampbell-wf** [Workiva/go-datastructures#99]
Example failures caused by a race condition in the ctrie tests:

https://travis-ci.org/Workiva/go-datastructures/jobs/69646914
https://travis-ci.org/Workiva/go-datastructures/jobs/69537489
https://travis-ci.org/Workiva/go-datastructures/jobs/69537490

I can't reproduce these locally. The first two builds (on Go 1.3) never terminated and were killed by Travis after ten minutes. The last build was on Go 1.4 and shows a ctrie unit test failure.

Any ideas @dustinhiatt-wf?

**Comment by dustinhiatt-wf** [comment]
The race conditions I've seen can be highly sensitive to the environment.  I've also seen the -race flag illuminate threadsafe race conditions.  I'm guessing it's a real issue.

**Comment by deden88** [comment]
Request

**Comment by tylertreat-wf** [comment]
Looking into it.

**Comment by tylertreat-wf** [comment]
Should be fixed with https://github.com/Workiva/go-datastructures/pull/100.
